### ISSUE TITLE
GRW Button on "Second" browser window doesn't work correctly

### ISSUE THREAD

**Issue by SaintPeter74** [Ajnasz/grwatcher#6]
I was having issues that the GRW button I have on my toolbar was weirdly unresponsive:  Clicking on it doesn't take me to Google Reader and none of the functions work when I Right-Click, although it does bring up the toolbar.

I have been running with two windows open and I discovered that the same button on the OTHER window, which appears to be the first or "primary" window works fine.  I can click to open the window and all of the right click functions work.

As per your instructions in another thread, I opened the error console and I get the following error:
`Error: GRW.onToolbarButtonAdd is not a function
Source File: chrome://browser/content/browser.xul
Line: 1`

I get multiples of this error - one triggers whenever I do at least one of the following:
Mouse-over the GRW button
Right Click the GRW button
Mouse-over any of the feeds listed in the right click drop down
Click any of the right-click functions

**Comment by SaintPeter74** [comment]
Forgot to add:
Firefox 6.0.1
GRW 1.5.2
Windows 7 64-bit

**Comment by Ajnasz** [comment]
Thank you, I will take a look at it.

**Comment by Ajnasz** [comment]
Did you see any other error message before this?

**Comment by SaintPeter74** [comment]
No, at least none that were obviously related to GRW.  I cleared the error log, selected "ALL" and attempted to interact with the button on the second window - it spawned the previously described errors.  If there were an error on startup I don't know how to see it.

This is interesting:  I spawned a third window (Ctrl-N) and its button works just fine.  I wonder if its an issue with the session manager (I use it to restore prior tabs/windows on statup)?  Or possibly an interaction with another plugin.

I presume you can't reproduce?

**Comment by Ajnasz** [comment]
Yes, I can't reproduce it. :)
I killed my Firefox and tried it with session manager too but the
extension was working.

Strange this issue, because basically it means that the js of the
extension wasn't loaded. I thought maybe some JS error occured, which
blocked to load the js of the GRW extension.

**Comment by SaintPeter74** [comment]
Is there a way to watch the JS errors on startup?  My bet would be interference with another one of my plugins but, as you say, there should be some sort of error that helps us determine when/what.  I'm a programmer, but not so much with FF plugin development.

**Comment by Ajnasz** [comment]
Usually the error console shows the error messages. I also installed the console2 add-on, it makes easier to filter messages: https://addons.mozilla.org/en-US/firefox/addon/console%C2%B2/.

**Comment by Ajnasz** [comment]
I think the issue has been fixed.
I got an email from another guy and he said that he can reproduce if he opens the new window by dragging a tab. If I did it the same happened to me. If you try the development version now http://ajnasz.hu/files/dev/grwatcher.xpi it should work for you too!

**Comment by SaintPeter** [comment]
Now if only it were flagged for compatibility with FF 8.0 . . .

**Comment by Ajnasz** [comment]
On Tue, 2011-Nov-08 at 15:52, SaintPeter wrote:

> Now if only it were flagged for compatibility with FF 8.0 . . .

Sorry, try it now :)

## 

Lajos Koszti

**Comment by SaintPeter** [comment]
I installed the dev version you link to above and it does not appear to fix the issue.  The button is still partially unresponsive on my second window.

**Comment by Ajnasz** [comment]
On Wed, 2011-Nov-09 at 14:53, SaintPeter wrote:

> I installed the dev version you link to above and it does not appear to fix the issue.  The button is still partially unresponsive on my second window.

Hi,

Could you try again? (Install from the same link.)

The error message won't show up again (I really hope :) )

Anyway, could you tell me what's the value of
extensions.grwatcher.delaystart property? You can find it on the
about:config page.

## Thanks

Lajos Koszti

**Comment by SaintPeter** [comment]
Ok, installed it.

I did the restart as needed to activate the new version.  On bringup there were 3 windows (I had 3 open).  On two of the windows it worked fine, on the third it did not work - same as before.

The value of extensions.grwatcher.delaystart is 0.

I thought of something which may be interfering - I'm using TabMixPlus to handle my session restore.  It's possible that this is causing a different tab/window restore functionality.  I'll experiment with using the build in restore.

**Comment by Ajnasz** [comment]
> I thought of something which may be interfering - I'm using TabMixPlus to handle my session restore.  It's possible that this is causing a different tab/window restore functionality.  I'll experiment with using the build in restore.

Maybe, but I don't really think.

I have a last idea about the reason. Please install it again.

The version should be 1.6-111111192915-master.7450899

Thanks

## 

Lajos Koszti

**Comment by SaintPeter** [comment]
The latest version appears to have fixed the problem, at least as near as I can tell.

Thanks!
